### ISSUE TITLE
AzureMonitorSpanExporter v0.5.0 does not work with OpenTelemetry v0.15b0

### ISSUE THREAD

**Issue by stschenk** [microsoft/opentelemetry-azure-monitor-python#132]
I have upgraded to the latest OpenTelemetry v0.15b0 and am already on the latest opentelemetry-azure-monitor v.0.5.0.

At startup, I am seeing the following exception:
     from azure_monitor import AzureMonitorSpanExporter
         File "/usr/local/lib/python3.6/dist-packages/azure_monitor/__init__.py", line 3, in <module>
     from azure_monitor.export.metrics import AzureMonitorMetricsExporter
         File "/usr/local/lib/python3.6/dist-packages/azure_monitor/export/__init__.py", line 14, in <module>
     from opentelemetry.trace.status import StatusCanonicalCode
     ImportError: cannot import name 'StatusCanonicalCode'

Looks like the latest version of OpenTelemetry has rename StatusCanonicalCode to StatusCode?

**Comment by lzchen** [comment]
Hey @stschenk 
We are in the process of migrating the code for opentelemetry-azure-monitor to a different [repo](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/monitor/opentelemetry-exporter-azuremonitor) under the `Azure` organization. Development for the exporters have been paused temporarily until this has been done. Keep an eye out in the new repo for when these changes will be fixed!

**Comment by stschenk** [comment]
Great! Thanks!

**Comment by lzchen** [comment]
The new repo exists [here](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/monitor/azure-opentelemetry-exporter-azuremonitor). Please submit issues under that repo.
